import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    // Generated by `bunx shadcn@latest add`, rewritten on every `bun run upgrade`.
    // Matches the same exclusion in oxlint.config.ts.
    "**/packages/ui/src/components",
    "**/packages/ui/src/hooks",
    "**/packages/ui/src/lib",
    // Skills are vendored from upstream repos and pinned by content hash in
    // skills-lock.json. Reformatting them would invalidate the hash on sync.
    "**/.agents/skills",
    "**/.claude/skills",
    // Vendored from dmmulroy/anti-slop. Ours to edit, but it keeps upstream
    // style. Matches the same exclusion in oxlint.config.ts.
    "tools/oxlint/anti-slop",
  ],
});
