import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";

/**
 * `packages/ui/src/{components,hooks,lib}` is generated by `bunx shadcn add` and
 * rewritten wholesale on every `bun run upgrade`. Linting it reports on code we
 * do not author and cannot keep fixed. Mirrored in `oxfmt.config.ts`.
 */
const GENERATED_UI = [
  "**/packages/ui/src/components",
  "**/packages/ui/src/hooks",
  "**/packages/ui/src/lib",
];

/**
 * Skills, hooks and settings installed by coding agents. Vendored assets, not
 * application source. Mirrored in `oxfmt.config.ts`.
 */
const AGENT_TOOLING = [
  ".agent/**",
  ".agents/**",
  ".claude/**",
  ".codex/**",
  ".continue/**",
  ".cursor/**",
  ".gemini/**",
  ".opencode/**",
  ".pi/**",
  ".roo/**",
  ".windsurf/**",
];

/**
 * The anti-slop rules themselves. Vendored from dmmulroy/anti-slop and ours to
 * edit, but they follow upstream style, not this repo's. Mirrored in
 * `oxfmt.config.ts`.
 */
const ANTI_SLOP_PLUGIN = "tools/oxlint/anti-slop/**";

export default defineConfig({
  extends: [core, next],
  ignorePatterns: [
    ...core.ignorePatterns,
    ...GENERATED_UI,
    ...AGENT_TOOLING,
    ANTI_SLOP_PLUGIN,
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
  ],
  overrides: [
    {
      files: ["**/*.{test,spec}.{ts,tsx}"],
      rules: {
        "no-magic-numbers": "off",
      },
    },
  ],
  rules: {
    // Opinionated rules against low-evidence TypeScript: `unknown` in public
    // signatures, chained assertions, `typeof` narrowing of known values.
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    // `import * as X` is the documented shape for several dependencies.
    "import/no-namespace": "off",
    // Logging is the point in scripts and in server-side code.
    "no-console": "off",
    // Advisory, not blocking: an unexplained literal usually wants a named
    // constant, but 0/1/-1 are self-describing. `ignore` restores the numbers
    // Biome's `noMagicNumbers` exempted by default before the migration.
    "no-magic-numbers": ["warn", { ignore: [-1, 0, 1] }],
    // Each workspace package exposes its public surface through a barrel.
    "oxc/no-barrel-file": "off",
    "typescript/consistent-type-definitions": ["error", "interface"],
  },
});
