import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";

/**
 * `packages/ui/src/{components,hooks,lib}` is generated by `bunx shadcn add` and
 * rewritten wholesale on every `bun run upgrade`. Linting it reports on code we
 * do not author and cannot keep fixed. Mirrored in `oxfmt.config.ts`.
 */
const GENERATED_UI = [
  "**/packages/ui/src/components",
  "**/packages/ui/src/hooks",
  "**/packages/ui/src/lib",
];

export default defineConfig({
  extends: [core, next],
  ignorePatterns: [...core.ignorePatterns, ...GENERATED_UI],
  overrides: [
    {
      files: ["**/*.{test,spec}.{ts,tsx}"],
      rules: {
        "no-magic-numbers": "off",
      },
    },
  ],
  rules: {
    // `import * as X` is the documented shape for several dependencies.
    "import/no-namespace": "off",
    // Logging is the point in scripts and in server-side code.
    "no-console": "off",
    // Advisory, not blocking: an unexplained literal usually wants a named
    // constant, but 0/1/-1 are self-describing. `ignore` restores the numbers
    // Biome's `noMagicNumbers` exempted by default before the migration.
    "no-magic-numbers": ["warn", { ignore: [-1, 0, 1] }],
    // Each workspace package exposes its public surface through a barrel.
    "oxc/no-barrel-file": "off",
    "typescript/consistent-type-definitions": ["error", "interface"],
  },
});
